Repository swcarpentry/git-novice, pull requests merged in 2018-05, with the labels that each got.

#513 Minor changes to _episodes/03-create.md
  _episodes/03-create.md
Labels: type:enhancement

#512 Minor changes to _episodes/02-setup.md
  _episodes/02-setup.md
Labels: type:enhancement

#511 Update _config.yml
  _config.yml
Labels: type:formatting

#515 Minor fixes to _episodes/04-changes.md
  _episodes/04-changes.md
Labels: type:enhancement

#517 Include detached HEAD message
  _episodes/05-history.md
Labels: status:pr-in-review, type:clarification

#518 Rewrite the solution for Understanding Workflow and History
  _episodes/05-history.md
Labels: status:pr-in-review, type:enhancement

#527 ENH: Repeat local repo diagram in github lesson
  _episodes/07-github.md
Labels: status:in-progress, type:enhancement

#530 make sure planets folder is created in user's Desktop directory
  _episodes/03-create.md
Labels: type:clarification
