Repository swcarpentry/git-novice, pull requests merged in 2019-07, with the labels that each got.

#434 issue #370 - Improved wording for 'Reverting a commit'
  _episodes/05-history.md
Labels: status:changes requested, type:enhancement

#492 Updates to episodes 02 and 07
  _episodes/02-setup.md
  _episodes/07-github.md
Labels: status:changes requested, status:in progress, type:enhancement

#561 added github large file support challenge to episode 10
  _episodes/10-open.md
Labels: status:changes requested, status:in progress
